backend:
  name: git-gateway
  branch: master
  repo: mikeyslice/esports-medium
  
# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under images/uploads

# Displays link to main site in backend
display_url: https://esportsmedium.com
