backend:
  name: git-gateway
  branch: master
  repo: mikeyslice/esports-medium
  
# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under images/uploads

# Displays link to main site in backend
display_url: https://esportsmedium.com

collections:
  - name: "pages"
    label: "Skillz Match Codes"
    delete: false
    description: >
      You can update your Skillz Match Codes section here.
    files:
      - label: "Skillz Match Codes"
        name: "skillz-match-codes"
        file: "_includes/pages/skillz-match-codes.html"
        fields:
          - {label: "Content", name: "body", widget: "markdown", hint: "Page content goes here."}

